#!/bin/sh
# ─────────────────────────────────────────────────────────────────────
# inject-env.sh
# Netlify build script: copies all source files to dist/ and
# generates assets/js/config.js with real values from env vars.
# ─────────────────────────────────────────────────────────────────────

set -e

echo "==> Creating dist/ directory..."
rm -rf dist
mkdir -p dist/assets/js dist/assets/css dist/scripts

echo "==> Copying static files..."
cp index.html  dist/
cp admin.html  dist/

# Copy CSS files individually (avoid cp -r directory quirks on build hosts)
for f in assets/css/*.css; do
  fname=$(basename "$f")
  cp "$f" "dist/assets/css/$fname"
  echo "    copied css: $fname"
done

# Copy all JS except config.js (we generate it below)
for f in assets/js/*.js; do
  fname=$(basename "$f")
  if [ "$fname" != "config.js" ] && [ "$fname" != "config.template.js" ]; then
    cp "$f" "dist/assets/js/$fname"
    echo "    copied js: $fname"
  fi
done

echo "==> Injecting environment variables into config.js..."

cat > dist/assets/js/config.js << JSEOF
/**
 * config.js — Auto-generated by Netlify build (inject-env.sh)
 * DO NOT edit this file directly.
 */
const CONFIG = {
  SUPABASE_URL:         '${SUPABASE_URL}',
  SUPABASE_ANON_KEY:    '${SUPABASE_ANON_KEY}',
  SUPABASE_SERVICE_KEY: '${SUPABASE_SERVICE_KEY}',
  ADMIN_PASSWORD_HASH:  '${ADMIN_PASSWORD_HASH}',
  SITE_NAME:            'Freight Rate Portal',
  COMPANY_NAME:         'Aramex',
  VERSION:             '1.0.0',
  SESSION_TIMEOUT_MS:   28800000,
  ADMIN_PAGE_SIZE:      25,
};
Object.freeze(CONFIG);
JSEOF

echo "==> Build complete. Files in dist/:"
ls -R dist/
