#!/bin/sh
# ─────────────────────────────────────────────────────────────────────
# inject-env.sh
# Netlify/Cloudflare Pages build script: copies all source files to dist/
# and generates assets/js/config.js with real values from env vars.
# Also stamps a build version into all HTML script/link tags to bust
# browser cache after every deploy.
#
# Environment variables required:
#   SUPABASE_URL       — Supabase project URL
#   SUPABASE_ANON_KEY  — Supabase anon/public key
# ─────────────────────────────────────────────────────────────────────

set -e

# Build timestamp used as cache-busting version string (e.g. 20260517120000)
BUILD_VER=$(date -u +%Y%m%d%H%M%S)
echo "==> Build version: ${BUILD_VER}"

echo "==> Creating dist/ directory..."
rm -rf dist
mkdir -p dist/assets/js dist/assets/css dist/scripts

echo "==> Copying and versioning HTML files..."
for html in index.html admin.html; do
  # Append ?v=BUILD_VER to every local assets/js/*.js and assets/css/*.css reference
  sed \
    -e "s|assets/js/\([a-zA-Z0-9._-]*\.js\)\"|assets/js/\1?v=${BUILD_VER}\"|g" \
    -e "s|assets/css/\([a-zA-Z0-9._-]*\.css\)\"|assets/css/\1?v=${BUILD_VER}\"|g" \
    "$html" > "dist/$html"
  echo "    versioned html: $html"
done

# Copy CSS files individually
for f in assets/css/*.css; do
  fname=$(basename "$f")
  cp "$f" "dist/assets/css/$fname"
  echo "    copied css: $fname"
done

# Copy _headers for Cloudflare Pages (cache-control headers)
if [ -f "_headers" ]; then
  cp "_headers" "dist/_headers"
  echo "    copied _headers (Cloudflare Pages cache rules)"
fi

# Copy all JS except config.js (we generate it below)
for f in assets/js/*.js; do
  fname=$(basename "$f")
  if [ "$fname" != "config.js" ] && [ "$fname" != "config.template.js" ]; then
    cp "$f" "dist/assets/js/$fname"
    echo "    copied js: $fname"
  fi
done

echo "==> Injecting environment variables into config.js..."

cat > dist/assets/js/config.js << JSEOF
/**
 * config.js — Auto-generated by build (inject-env.sh)
 * Build: ${BUILD_VER}
 * DO NOT edit this file directly — it is overwritten on every build.
 *
 * Multi-account system (hardcoded — password hashes are not secrets):
 *   admin         | role: admin   | full access (incl. Settings)
 *   PVG_Pricing   | role: pricing | rates only
 *   PEK_Pricing   | role: pricing | rates only
 *   CAN_Pricing   | role: pricing | rates only
 */
const CONFIG = {
  // Supabase (from env vars)
  SUPABASE_URL:      '${SUPABASE_URL}',
  SUPABASE_ANON_KEY: '${SUPABASE_ANON_KEY}',

  // Multi-account config (hardcoded — SHA-256 hashes are not reversible)
  ACCOUNTS: {
    'admin': {
      hash: 'faffce77c92b11ccc8e5b2d7f12cfbde01a2ca50fd9b50d2b48494f27ae5ad4a',
      role: 'admin',
      label: 'Admin',
    },
    'PVG_Pricing': {
      hash: '20f645c703944a0027acf6fad92ec465247842450605c5406b50676ff0dcd5ea',
      role: 'pricing',
      label: 'PVG_Pricing',
    },
    'PEK_Pricing': {
      hash: '20f645c703944a0027acf6fad92ec465247842450605c5406b50676ff0dcd5ea',
      role: 'pricing',
      label: 'PEK_Pricing',
    },
    'CAN_Pricing': {
      hash: '20f645c703944a0027acf6fad92ec465247842450605c5406b50676ff0dcd5ea',
      role: 'pricing',
      label: 'CAN_Pricing',
    },
  },

  // Site settings
  SITE_NAME:     'Freight Rate Portal',
  COMPANY_NAME:  'Aramex',
  VERSION:       '${BUILD_VER}',

  // Session timeout: 8 hours
  SESSION_TIMEOUT_MS: 8 * 60 * 60 * 1000,

  // Admin table page size
  ADMIN_PAGE_SIZE: 25,
};

Object.freeze(CONFIG);
JSEOF

echo "==> Build complete (v${BUILD_VER}). Files in dist/:"
ls -R dist/
